name = "MyLeanProject"
version = "0.1.0"
defaultTargets = ["MyLeanProject"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "23c1716ff0bd678dc55f029da743429101b145e3"

[[lean_lib]]
name = "MyLeanProject"